---

- name: Ansible Playbook for configuring a brand new Raspberry Pi

  hosts: pi
  roles:
    - pi
  remote_user: pi
  become: yes

- name: Ansible Playbook for configuring homebridge

  hosts: homebridge
  roles:
    - homebridge
  remote_user: pi
  become: yes

- name: Ansible Playbook for configuring smstools

  hosts: smstools
  roles:
    - smstools
  remote_user: pi
  become: yes
