---
- name: 'set timezone to Europe/Berlin'
  timezone:
    name: Europe/Berlin

- name: 'Install prerequisites'
  apt: name={{item}} state=installed
  with_items:
    - wget
    - libavahi-compat-libdnssd-dev

- name: 'Install node.js'
  command: chdir=/root/ {{ item }}
  with_items:
    - wget https://nodejs.org/dist/v4.6.0/node-v4.6.0-linux-armv7l.tar.gz 
    - tar -xvf node-v4.6.0-linux-armv7l.tar.gz 
    - cp -fR /root/node-v4.6.0-linux-armv7l/bin/ /usr/local/
    - cp -fR /root/node-v4.6.0-linux-armv7l/lib/ /usr/local/
    - cp -fR /root/node-v4.6.0-linux-armv7l/share/ /usr/local/
    - cp -fR /root/node-v4.6.0-linux-armv7l/include/ /usr/local/
    - rm -R /root/node-v4.6.0-linux-armv7l.tar.gz      
  args:
    creates: /root/node-v4.6.0-linux-armv7l

- name: 'Install homebridge'  
  command: chdir=/root/ {{ item }}
  with_items:
    - sudo npm install -g --unsafe-perm homebridge 
    - sudo npm install forever -g
    - mkdir -p /home/pi/.homebridge
    - sudo npm install -g homebridge-fritz

- name: 'Configure homebridge'
  copy: src=./templates/homebridge/config.json dest=/home/pi/.homebridge/config.json mode=0600

- name: 'Configure homebridge init.d'
  copy: src=./templates/homebridge/homebridge dest=/etc/init.d/homebridge mode=0755

- name: '.homebridge owned by pi'
  file:
    path: /home/pi/.homebridge
    owner: pi
    group: pi    
    state: directory
    recurse: yes

- name: 'Enable homebridge'  
  command: update-rc.d homebridge defaults

- name: 'Start homebridge'  
  command: /etc/init.d/homebridge restart