---
- name: 'Update APT package cache'
  action: apt update_cache=yes

- name: 'Upgrade APT to the lastest packages'
  action: apt upgrade=safe

- name: 'Install the package "htop"'
  apt:
    name: htop
    state: present

- name: 'Generate SSH keys for pi'
  shell: ssh-keygen -b 2048 -t rsa -f /home/pi/.ssh/id_rsa -q -N ""
  args:
    creates: /home/pi/.ssh/id_rsa

- name: 'Set authorized key for user pi copying it from current user'
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: 'change owner of SSH keys to pi'  
  command: "chown -R pi:pi /home/pi/.ssh"
  changed_when: false

- name: 'Generate SSH keys for root'
  shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa

- name: 'Set authorized key for user root copying it from current user'
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: 'Make sure SSH is enabled'    
  service: name=ssh enabled=yes

- name: 'Reboot'
  command: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: 'Wait for Raspberry PI to come back'
  local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started delay=10
  become: false
